version: "3.6"
services:
  manifest_postgres:
      container_name: postgres_container_manifest 
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      restart: unless-stopped
      ports:
      - "5436:5432"
networks:
  default:
    external:
       name: minikube
volumes:
    postgres:
    pgadmin:
    go-modules:
    go-cache: