// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Product struct {
	ID          string
	Name        sql.NullString
	Description sql.NullString
	Color       sql.NullString
}
