// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"database/sql"
)

type UnprocessedMessage struct {
	EventID   string
	Delivered sql.NullInt64
	Service   sql.NullString
	Consumer  sql.NullString
	Payload   sql.NullString
	Outcome   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
