// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: unprocessedMessage.sql

package database

import (
	"context"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO unprocessed_messages(event_id, delivered, service, consumer, payload, outcome, created_at, updated_at)
VALUES ($1::TEXT, $2::BIGINT, $3::TEXT, $4::TEXT, $5::TEXT, $6::TEXT, NOW(),
        NOW())
`

type InsertMessageParams struct {
	EventID   string
	Delivered int64
	Service   string
	Consumer  string
	Payload   string
	Outcome   string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertMessage,
		arg.EventID,
		arg.Delivered,
		arg.Service,
		arg.Consumer,
		arg.Payload,
		arg.Outcome,
	)
	return err
}
